# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: ^micropython/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, starlette]

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.7.7.23
    hooks:
      - id: actionlint
        additional_dependencies: [pyflakes>=3.0.1]
        args: [-shellcheck=]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject[all,store]"]

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/zeevro/pyproject-toml-format
    rev: v0.0.2
    hooks:
      - id: pyproject-toml-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.5
    hooks:
      - id: uv-lock

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.29
    hooks:
      - id: pymarkdown
        args: [fix]
